/**
 * The hidden SVG <filter> that drives the Liquid Glass refraction.
 *
 * Render this ONCE, near the root of your app (e.g. in a server-rendered
 * root layout), not inside the glass component itself. Two reasons:
 *
 * 1. It's shared - every element using `.liquid-glass` references the same
 *    `#liquid-lens` filter by id, so it only needs to exist once per page.
 * 2. Hydration safety - if you render this inside a "use client" component,
 *    React may produce a different SVG tree on the server vs. the client
 *    on the first paint, which triggers a hydration mismatch error. A
 *    server component (or plain server-rendered markup) avoids this
 *    entirely because the filter is fully static.
 *
 * Usage (e.g. app/layout.tsx):
 *
 *   import { LiquidGlassFilter } from "@/components/LiquidGlassFilter"
 *
 *   export default function RootLayout({ children }) {
 *     return (
 *       <html>
 *         <body>
 *           <LiquidGlassFilter />
 *           {children}
 *         </body>
 *       </html>
 *     )
 *   }
 */

type LiquidGlassFilterProps = {
  /** Filter id, referenced from CSS as `url(#id)`. */
  id?: string
  /** Path to the displacement map PNG generated by generate-displacement-map.py. */
  mapSrc?: string
  /**
   * How strongly the backdrop bends, in pixels. MUST be negative for an
   * Apple-style magnifying lens - positive values produce a fish-eye /
   * pinch effect instead. Larger magnitude = stronger bend.
   */
  scale?: number
  /**
   * Adds chromatic aberration (color fringing at the edges) by running
   * the displacement three times at slightly different scales, once per
   * color channel, then recombining with `feBlend mode="screen"`. This is
   * subtle but is what sells the "real glass/lens" look up close. Set to
   * false for a slightly cheaper, color-neutral bend.
   */
  chromaticAberration?: boolean
}

export function LiquidGlassFilter({
  id = "liquid-lens",
  mapSrc = "/liquid-lens-map.png",
  scale = -42,
  chromaticAberration = true,
}: LiquidGlassFilterProps) {
  return (
    <svg
      aria-hidden="true"
      focusable="false"
      style={{ position: "absolute", width: 0, height: 0, pointerEvents: "none" }}
    >
      <filter id={id} colorInterpolationFilters="sRGB" x="0%" y="0%" width="100%" height="100%">
        <feImage href={mapSrc} preserveAspectRatio="none" x="0" y="0" width="100%" height="100%" result="map" />

        {chromaticAberration ? (
          <>
            <feDisplacementMap in="SourceGraphic" in2="map" scale={scale - 2} xChannelSelector="R" yChannelSelector="G" />
            <feColorMatrix type="matrix" values="1 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 1 0" result="dR" />

            <feDisplacementMap in="SourceGraphic" in2="map" scale={scale} xChannelSelector="R" yChannelSelector="G" />
            <feColorMatrix type="matrix" values="0 0 0 0 0  0 1 0 0 0  0 0 0 0 0  0 0 0 1 0" result="dG" />

            <feDisplacementMap in="SourceGraphic" in2="map" scale={scale + 2} xChannelSelector="R" yChannelSelector="G" />
            <feColorMatrix type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 1 0 0  0 0 0 1 0" result="dB" />

            <feBlend in="dR" in2="dG" mode="screen" result="dRG" />
            <feBlend in="dRG" in2="dB" mode="screen" />
          </>
        ) : (
          <feDisplacementMap in="SourceGraphic" in2="map" scale={scale} xChannelSelector="R" yChannelSelector="G" />
        )}
      </filter>
    </svg>
  )
}
